### ISSUE TITLE
Support for dotnet 5?

### ISSUE THREAD

**Issue by pcarrier** [krauthaufen/Adaptify#17]
Installation currently fails on SDK 5.0.102 with:

```
example.fsproj: [NU1202] Package adaptify 1.0.3 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package adaptify 1.0.3 supports:
  - netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any
  - netcoreapp2.2 (.NETCoreApp,Version=v2.2) / any
  - netcoreapp3.0 (.NETCoreApp,Version=v3.0) / any
  - netcoreapp3.1 (.NETCoreApp,Version=v3.1) / any
```

**Comment by haraldsteinlechner** [comment]
Late but at least one .net version later ;) .. just added targets net5/6 for the tool. i deployed a test version 1.0.10 out of the PR which should work without only net5/6.

**Comment by haraldsteinlechner** [comment]
this one is done and used in production. please re-open if the problem unexpectedly persists
