### ISSUE TITLE
Generated code does not build with VS 2022

### ISSUE THREAD

**Issue by hyazinthh** [krauthaufen/Adaptify#25]
Repository: https://github.com/aardvark-platform/aardvark.media

![Untitled](https://user-images.githubusercontent.com/39337420/147117962-41f179f9-306e-4f23-b193-3c6410203378.png)

Just make names in `as` patterns lower case?

**Comment by haraldsteinlechner** [comment]
fixed in 1.0.9 (https://github.com/krauthaufen/Adaptify/commit/d883979f56e416ad298399003ce7e8fbd3a62df1)

btw: aardvark.media was updated already accordingly.
